
###

GET https://sales4pro-berkemann-syncdatahost.azurewebsites.net/tables/syncshoppingcart?ZUMO-API-VERSION=2.0.0

###

GET https://sales4pro-solidus-syncdatahost.azurewebsites.net/tables/syncshoppingcart?ZUMO-API-VERSION=2.0.0

###

