//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyConveno.Toolkit.Sales4Pro.Client.BaseDataUpdates.Strings.de {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BaseDataUpdateResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaseDataUpdateResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyConveno.Toolkit.Sales4Pro.Client.BaseDataUpdates.Strings.de.BaseDataUpdateResou" +
                            "rces", typeof(BaseDataUpdateResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertreter.
        /// </summary>
        public static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikel Nr..
        /// </summary>
        public static string ArticleNo {
            get {
                return ResourceManager.GetString("ArticleNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einkaufsvereinigung.
        /// </summary>
        public static string Association {
            get {
                return ResourceManager.GetString("Association", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV-Nummer.
        /// </summary>
        public static string AssoMemberNumber {
            get {
                return ResourceManager.GetString("AssoMemberNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortiment.
        /// </summary>
        public static string Assortment {
            get {
                return ResourceManager.GetString("Assortment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EK.
        /// </summary>
        public static string BP {
            get {
                return ResourceManager.GetString("BP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kollektionsrabatt.
        /// </summary>
        public static string CollectionDiscount {
            get {
                return ResourceManager.GetString("CollectionDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farbe.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reklamationsrabatt.
        /// </summary>
        public static string ComplaintDiscount {
            get {
                return ResourceManager.GetString("ComplaintDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansprechpartner.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kundenartikel.
        /// </summary>
        public static string CustomerArticle {
            get {
                return ResourceManager.GetString("CustomerArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grundrabatt.
        /// </summary>
        public static string CustomerDiscount {
            get {
                return ResourceManager.GetString("CustomerDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kundennummer.
        /// </summary>
        public static string CustomerNumber {
            get {
                return ResourceManager.GetString("CustomerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summen pro Liefertermin.
        /// </summary>
        public static string DeliveryOrderValues {
            get {
                return ResourceManager.GetString("DeliveryOrderValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieferung an.
        /// </summary>
        public static string DeliveryTo {
            get {
                return ResourceManager.GetString("DeliveryTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieferbedingung.
        /// </summary>
        public static string DeliveryType {
            get {
                return ResourceManager.GetString("DeliveryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wunschtermin.
        /// </summary>
        public static string DesiredDeliveryDate {
            get {
                return ResourceManager.GetString("DesiredDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabatt.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Früheinteilerrabatt.
        /// </summary>
        public static string EarlyBirdDiscount {
            get {
                return ResourceManager.GetString("EarlyBirdDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EUR.
        /// </summary>
        public static string EUR {
            get {
                return ResourceManager.GetString("EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kostl..
        /// </summary>
        public static string FoC {
            get {
                return ResourceManager.GetString("FoC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnung an.
        /// </summary>
        public static string InvoiceTo {
            get {
                return ResourceManager.GetString("InvoiceTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebietsvertreter.
        /// </summary>
        public static string MainAgent {
            get {
                return ResourceManager.GetString("MainAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auftragsbestätigung.
        /// </summary>
        public static string OrderConfirmation {
            get {
                return ResourceManager.GetString("OrderConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auftrageingangsbestätigung.
        /// </summary>
        public static string OrderProposal {
            get {
                return ResourceManager.GetString("OrderProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellformular.
        /// </summary>
        public static string OrderProposalForm {
            get {
                return ResourceManager.GetString("OrderProposalForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellübersicht.
        /// </summary>
        public static string OrderProposalPreview {
            get {
                return ResourceManager.GetString("OrderProposalPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string OrderProposalPreviewNolte {
            get {
                return ResourceManager.GetString("OrderProposalPreviewNolte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auftragsart.
        /// </summary>
        public static string OrderType {
            get {
                return ResourceManager.GetString("OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auftragswert.
        /// </summary>
        public static string OrderValue {
            get {
                return ResourceManager.GetString("OrderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seite {0} von {1}.
        /// </summary>
        public static string PageXofX {
            get {
                return ResourceManager.GetString("PageXofX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlungsbedingungen.
        /// </summary>
        public static string PaymentTerms {
            get {
                return ResourceManager.GetString("PaymentTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vorl. Auftragsnummer.
        /// </summary>
        public static string PreliminaryOrderNo {
            get {
                return ResourceManager.GetString("PreliminaryOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vororderrabatt.
        /// </summary>
        public static string PreOrderDiscount {
            get {
                return ResourceManager.GetString("PreOrderDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menge.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mengenrabatt.
        /// </summary>
        public static string QuantityDiscount {
            get {
                return ResourceManager.GetString("QuantityDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertig.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bemerkung.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UVP.
        /// </summary>
        public static string RRP {
            get {
                return ResourceManager.GetString("RRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muster.
        /// </summary>
        public static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saison.
        /// </summary>
        public static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setze Liefertermin nicht vor.
        /// </summary>
        public static string SetDeliveryNotBefore {
            get {
                return ResourceManager.GetString("SetDeliveryNotBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Größengang.
        /// </summary>
        public static string SizeRange {
            get {
                return ResourceManager.GetString("SizeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UstID.
        /// </summary>
        public static string TaxID {
            get {
                return ResourceManager.GetString("TaxID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vielen Dank für Ihren Auftrag..
        /// </summary>
        public static string ThankYouForYourOrder {
            get {
                return ResourceManager.GetString("ThankYouForYourOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ges.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamt Menge.
        /// </summary>
        public static string TotalQuantity {
            get {
                return ResourceManager.GetString("TotalQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamt Summe.
        /// </summary>
        public static string TotalValue {
            get {
                return ResourceManager.GetString("TotalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade ....
        /// </summary>
        public static string UpdateData {
            get {
                return ResourceManager.GetString("UpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates verfügbar.
        /// </summary>
        public static string UpdatesAvailable {
            get {
                return ResourceManager.GetString("UpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valutatage.
        /// </summary>
        public static string Valuta {
            get {
                return ResourceManager.GetString("Valuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weite.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Auftrags Nr..
        /// </summary>
        public static string YourOrderNumber {
            get {
                return ResourceManager.GetString("YourOrderNumber", resourceCulture);
            }
        }
    }
}
